[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci --prefer-offline --no-audit --legacy-peer-deps"
]
cacheDirectories = ["node_modules"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run prisma:generate:prod",
  "npm run build"
]
cacheDirectories = [
  "node_modules/.cache",
  ".swc",
  "dist"
]

[build]
timeout = 600

[start]
cmd = "npm run start"
