[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "bun"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "bun install --frozen-lockfile",
  "bunx prisma generate --schema=./prisma/schema.prod.prisma",
  "bun run build"
]

[start]
cmd = "bun run start"
