// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Use production schema (PostgreSQL) in production, dev schema (SQLite) in development
const isProd = process.env.NODE_ENV === "production";
const schemaPath = isProd ? "prisma/schema.prod.prisma" : "prisma/schema.prisma";
const migrationsPath = isProd ? "prisma/migrations-prod" : "prisma/migrations";

export default defineConfig({
  schema: schemaPath,
  migrations: {
    path: migrationsPath,
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
