import { Injectable, NotFoundException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PrismaService } from '../prisma/prisma.service';

type Locale = 'es' | 'en';

// Terminal-failure statuses that should be watermarked as VOID so a printed
// PDF can't be confused with a real receipt. Loans use 'CANCELLED' and
// transfers use 'CANCELLED' or 'REJECTED'.
const VOID_STATUSES = new Set(['CANCELLED', 'REJECTED']);

interface ReceiptItem {
  name: string;
  serviceTag?: string | null;
  quantity: number;
  unitPrice: number | null;
  currency: string | null;
}

interface ReceiptContext {
  documentType: 'loan' | 'transfer' | 'outflow' | 'sale';
  id: string;
  name: string | null;
  status: string;
  sourceWarehouse: string;
  destinationWarehouse: string;
  createdAt: Date;
  dueDate?: Date | null;
  createdBy: string;
  items: ReceiptItem[];
  notes?: string | null;
  // Outflow-specific metadata
  reason?: string | null;
  warehouseLabel?: string | null;
  // Sale-specific metadata
  customerName?: string | null;
  customerType?: string | null;
}

const STRINGS = {
  es: {
    loanTitle: 'COMPROBANTE DE PRÉSTAMO',
    transferTitle: 'COMPROBANTE DE TRANSFERENCIA',
    outflowTitle: 'COMPROBANTE DE SALIDA',
    saleTitle: 'COMPROBANTE DE VENTA',
    voidCancelled: 'CANCELADO',
    voidRejected: 'RECHAZADO',
    id: 'ID',
    name: 'Nombre',
    status: 'Estado',
    from: 'Bodega origen',
    to: 'Bodega destino',
    warehouse: 'Bodega',
    reason: 'Motivo',
    customer: 'Cliente',
    customerType: 'Tipo de cliente',
    created: 'Fecha de creación',
    dueDate: 'Fecha de devolución',
    createdBy: 'Creado por',
    notes: 'Notas',
    items: 'Productos',
    colItem: 'Producto',
    colTag: 'Service tag',
    colQty: 'Cant.',
    colUnit: 'Precio unit.',
    colSubtotal: 'Subtotal',
    total: 'Total',
    noPrice: '—',
    signaturesHeader: 'Firmas',
    signedBy: 'Entrega',
    receivedBy: 'Recibe',
    authorizedBy: 'Autoriza',
    attendedBy: 'Atendido por',
    nameLine: 'Nombre',
    dateLine: 'Fecha',
    autoGenerated: 'Documento generado automáticamente',
    page: 'Página',
    reasons: {
      DAMAGED: 'Dañado',
      LOST: 'Perdido',
      EXPIRED: 'Vencido',
      CONSUMED: 'Consumo interno',
      SOLD: 'Venta',
      OTHER: 'Otro',
    } as Record<string, string>,
    customerTypes: {
      WHOLESALE: 'Mayorista',
      DISTRIBUTOR: 'Distribuidor',
      RETAIL: 'Cliente final',
    } as Record<string, string>,
  },
  en: {
    loanTitle: 'LOAN RECEIPT',
    transferTitle: 'TRANSFER RECEIPT',
    outflowTitle: 'OUTFLOW RECEIPT',
    saleTitle: 'SALE RECEIPT',
    voidCancelled: 'CANCELLED',
    voidRejected: 'REJECTED',
    id: 'ID',
    name: 'Name',
    status: 'Status',
    from: 'Source warehouse',
    to: 'Destination warehouse',
    warehouse: 'Warehouse',
    reason: 'Reason',
    customer: 'Customer',
    customerType: 'Customer type',
    created: 'Created at',
    dueDate: 'Due date',
    createdBy: 'Created by',
    notes: 'Notes',
    items: 'Items',
    colItem: 'Item',
    colTag: 'Service tag',
    colQty: 'Qty',
    colUnit: 'Unit price',
    colSubtotal: 'Subtotal',
    total: 'Total',
    noPrice: '—',
    signaturesHeader: 'Signatures',
    signedBy: 'Issued by',
    receivedBy: 'Received by',
    authorizedBy: 'Authorized by',
    attendedBy: 'Attended by',
    nameLine: 'Name',
    dateLine: 'Date',
    autoGenerated: 'Auto-generated document',
    page: 'Page',
    reasons: {
      DAMAGED: 'Damaged',
      LOST: 'Lost',
      EXPIRED: 'Expired',
      CONSUMED: 'Consumed',
      SOLD: 'Sold',
      OTHER: 'Other',
    } as Record<string, string>,
    customerTypes: {
      WHOLESALE: 'Wholesale',
      DISTRIBUTOR: 'Distributor',
      RETAIL: 'Retail',
    } as Record<string, string>,
  },
} as const;

@Injectable()
export class PdfReceiptsService {
  constructor(private readonly prisma: PrismaService) {}

  async generateLoanReceipt(loanId: string, locale: Locale = 'es'): Promise<Buffer> {
    const loan = await this.prisma.loan.findUnique({
      where: { id: loanId },
      include: {
        sourceWarehouse: { select: { name: true } },
        destinationWarehouse: { select: { name: true } },
        createdBy: { select: { name: true, email: true } },
        items: {
          include: {
            inventoryItem: { select: { name: true, serviceTag: true, price: true, currency: true } },
          },
        },
      },
    });

    if (!loan) throw new NotFoundException('Loan not found');

    return this.render({
      documentType: 'loan',
      id: loan.id,
      name: loan.name,
      status: loan.status,
      sourceWarehouse: loan.sourceWarehouse?.name ?? '',
      destinationWarehouse: loan.destinationWarehouse?.name ?? '',
      createdAt: loan.createdAt,
      dueDate: loan.dueDate,
      createdBy: loan.createdBy?.name || loan.createdBy?.email || '',
      items: loan.items.map((li) => ({
        name: li.inventoryItem?.name ?? '',
        serviceTag: li.inventoryItem?.serviceTag,
        quantity: li.quantity,
        unitPrice: li.inventoryItem?.price ?? null,
        currency: li.inventoryItem?.currency ?? null,
      })),
      notes: loan.notes,
    }, locale);
  }

  async generateOutflowReceipt(outflowId: string, locale: Locale = 'es'): Promise<Buffer> {
    const outflow = await this.prisma.outflow.findUnique({
      where: { id: outflowId },
      include: {
        warehouse: { select: { name: true } },
        createdBy: { select: { name: true, email: true } },
        items: {
          include: {
            inventoryItem: { select: { name: true, serviceTag: true } },
          },
        },
      },
    });

    if (!outflow) throw new NotFoundException('Outflow not found');

    return this.render({
      documentType: 'outflow',
      id: outflow.id,
      name: outflow.name,
      status: outflow.status,
      sourceWarehouse: outflow.warehouse?.name ?? '',
      destinationWarehouse: '',
      warehouseLabel: outflow.warehouse?.name ?? '',
      reason: outflow.reason,
      createdAt: outflow.createdAt,
      createdBy: outflow.createdBy?.name || outflow.createdBy?.email || '',
      items: outflow.items.map((line) => ({
        // Prefer snapshot fields — they survive item renames and deletions.
        name: line.itemName ?? line.inventoryItem?.name ?? '',
        serviceTag: line.serviceTag ?? line.inventoryItem?.serviceTag,
        quantity: line.quantity,
        unitPrice: line.unitPrice ?? null,
        currency: line.currency ?? null,
      })),
      notes: outflow.notes,
    }, locale);
  }

  async generateSaleReceipt(saleId: string, locale: Locale = 'es'): Promise<Buffer> {
    const sale = await this.prisma.sale.findUnique({
      where: { id: saleId },
      include: {
        warehouse: { select: { name: true } },
        createdBy: { select: { name: true, email: true } },
        items: {
          include: {
            inventoryItem: { select: { name: true, serviceTag: true } },
          },
        },
      },
    });

    if (!sale) throw new NotFoundException('Sale not found');

    return this.render({
      documentType: 'sale',
      id: sale.id,
      name: sale.name,
      status: sale.status,
      sourceWarehouse: sale.warehouse?.name ?? '',
      destinationWarehouse: '',
      warehouseLabel: sale.warehouse?.name ?? '',
      customerName: sale.customerName,
      customerType: sale.customerType,
      createdAt: sale.createdAt,
      createdBy: sale.createdBy?.name || sale.createdBy?.email || '',
      items: sale.items.map((line) => ({
        // Prefer snapshot fields — they survive item renames and deletions.
        name: line.itemName ?? line.inventoryItem?.name ?? '',
        serviceTag: line.serviceTag ?? line.inventoryItem?.serviceTag,
        quantity: line.quantity,
        unitPrice: line.unitPrice ?? null,
        currency: line.currency ?? null,
      })),
      notes: sale.notes,
    }, locale);
  }

  async generateTransferReceipt(transferId: string, locale: Locale = 'es'): Promise<Buffer> {
    const transfer = await this.prisma.transferRequest.findUnique({
      where: { id: transferId },
      include: {
        sourceWarehouse: { select: { name: true } },
        destinationWarehouse: { select: { name: true } },
        requestedBy: { select: { name: true, email: true } },
        items: {
          include: {
            inventoryItem: { select: { name: true, serviceTag: true, price: true, currency: true } },
          },
        },
      },
    });

    if (!transfer) throw new NotFoundException('Transfer request not found');

    return this.render({
      documentType: 'transfer',
      id: transfer.id,
      name: transfer.name,
      status: transfer.status,
      sourceWarehouse: transfer.sourceWarehouse?.name ?? '',
      destinationWarehouse: transfer.destinationWarehouse?.name ?? '',
      createdAt: transfer.createdAt,
      createdBy: transfer.requestedBy?.name || transfer.requestedBy?.email || '',
      items: transfer.items.map((li) => ({
        name: li.inventoryItem?.name ?? '',
        serviceTag: li.inventoryItem?.serviceTag,
        quantity: li.quantity,
        // TransferRequestItem doesn't currently carry per-line price; fall back to the item's price.
        unitPrice: li.inventoryItem?.price ?? null,
        currency: li.inventoryItem?.currency ?? null,
      })),
      notes: transfer.notes,
    }, locale);
  }

  private render(ctx: ReceiptContext, locale: Locale): Promise<Buffer> {
    const t = STRINGS[locale];
    const dateLocale = locale === 'en' ? 'en-US' : 'es-HN';
    const fmtDate = (d: Date) =>
      d.toLocaleString(dateLocale, {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    const fmtAmount = (amount: number | null, currency: string | null) =>
      amount == null ? t.noPrice : `${currency ?? ''} ${amount.toFixed(2)}`.trim();

    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      // bufferPages so we can stamp the void watermark across every page once
      // the body has been laid out.
      const doc = new PDFDocument({ size: 'LETTER', margin: 50, bufferPages: true });
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      const title =
        ctx.documentType === 'loan'
          ? t.loanTitle
          : ctx.documentType === 'transfer'
            ? t.transferTitle
            : ctx.documentType === 'sale'
              ? t.saleTitle
              : t.outflowTitle;
      doc.fontSize(18).font('Helvetica-Bold').text(title, { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').fillColor('#666666')
        .text(`${t.id}: ${ctx.id}`, { align: 'center' });
      doc.fillColor('#000000');
      doc.moveDown(1.5);

      // Metadata block (two columns)
      const metaTop = doc.y;
      const colWidth = (doc.page.width - 100) / 2;
      const left = 50;
      const right = left + colWidth + 10;

      const writeRow = (label: string, value: string, y: number, x: number) => {
        doc.font('Helvetica-Bold').fontSize(9).fillColor('#555555').text(label, x, y, { width: colWidth - 10 });
        doc.font('Helvetica').fontSize(11).fillColor('#000000').text(value || '—', x, y + 12, { width: colWidth - 10 });
      };

      writeRow(t.name, ctx.name ?? '—', metaTop, left);
      writeRow(t.status, ctx.status, metaTop, right);

      if (ctx.documentType === 'outflow') {
        writeRow(t.warehouse, ctx.warehouseLabel ?? ctx.sourceWarehouse, metaTop + 42, left);
        const reasonLabel = ctx.reason ? (t.reasons[ctx.reason] ?? ctx.reason) : '—';
        writeRow(t.reason, reasonLabel, metaTop + 42, right);
      } else if (ctx.documentType === 'sale') {
        writeRow(t.warehouse, ctx.warehouseLabel ?? ctx.sourceWarehouse, metaTop + 42, left);
        const typeLabel = ctx.customerType
          ? (t.customerTypes[ctx.customerType] ?? ctx.customerType)
          : '—';
        writeRow(t.customerType, typeLabel, metaTop + 42, right);
      } else {
        writeRow(t.from, ctx.sourceWarehouse, metaTop + 42, left);
        writeRow(t.to, ctx.destinationWarehouse, metaTop + 42, right);
      }

      writeRow(t.created, fmtDate(ctx.createdAt), metaTop + 84, left);
      if (ctx.dueDate) writeRow(t.dueDate, fmtDate(ctx.dueDate), metaTop + 84, right);
      // Reuse the right slot (free for sales — no due date) for the customer name.
      if (ctx.documentType === 'sale') {
        writeRow(t.customer, ctx.customerName ?? '—', metaTop + 84, right);
      }

      writeRow(t.createdBy, ctx.createdBy, metaTop + 126, left);

      doc.y = metaTop + 168;
      doc.x = left;

      // Items table
      doc.moveDown(0.5);
      doc.font('Helvetica-Bold').fontSize(12).fillColor('#000000').text(t.items);
      doc.moveDown(0.3);

      const tableTop = doc.y;
      const colItem = left;
      const colTag = left + 200;
      const colQty = left + 320;
      const colUnit = left + 360;
      const colSub = left + 445;

      doc.font('Helvetica-Bold').fontSize(9).fillColor('#444444');
      doc.text(t.colItem, colItem, tableTop, { width: 195 });
      doc.text(t.colTag, colTag, tableTop, { width: 115 });
      doc.text(t.colQty, colQty, tableTop, { width: 35, align: 'right' });
      doc.text(t.colUnit, colUnit, tableTop, { width: 80, align: 'right' });
      doc.text(t.colSubtotal, colSub, tableTop, { width: 70, align: 'right' });

      doc.moveTo(left, tableTop + 14).lineTo(doc.page.width - 50, tableTop + 14).strokeColor('#cccccc').stroke();

      let cursor = tableTop + 20;
      // One running total per currency; items with no price contribute to nothing.
      // Items priced without a currency (currency = null) get bucketed under '' so they
      // don't accidentally merge with USD/HNL/etc.
      const totalsByCurrency = new Map<string, number>();

      doc.font('Helvetica').fontSize(10).fillColor('#000000');
      for (const item of ctx.items) {
        if (cursor > doc.page.height - 200) {
          doc.addPage();
          cursor = 50;
        }
        const unit = item.unitPrice;
        const sub = unit != null ? unit * item.quantity : null;
        if (sub != null) {
          const key = item.currency ?? '';
          totalsByCurrency.set(key, (totalsByCurrency.get(key) ?? 0) + sub);
        }

        doc.text(item.name || '—', colItem, cursor, { width: 195 });
        doc.text(item.serviceTag ?? '—', colTag, cursor, { width: 115 });
        doc.text(String(item.quantity), colQty, cursor, { width: 35, align: 'right' });
        doc.text(fmtAmount(unit, item.currency), colUnit, cursor, { width: 80, align: 'right' });
        doc.text(fmtAmount(sub, item.currency), colSub, cursor, { width: 70, align: 'right' });
        cursor += 18;
      }

      // Totals — one row per currency present. If none have prices, show a single em-dash.
      doc.moveTo(colUnit, cursor + 4).lineTo(doc.page.width - 50, cursor + 4).strokeColor('#cccccc').stroke();
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#000000');

      if (totalsByCurrency.size === 0) {
        doc.text(t.total, colUnit, cursor + 10, { width: 80, align: 'right' });
        doc.text(t.noPrice, colSub, cursor + 10, { width: 70, align: 'right' });
        cursor += 26;
      } else {
        // Stable order: known currencies first, then alphabetical
        const entries = Array.from(totalsByCurrency.entries()).sort(([a], [b]) => a.localeCompare(b));
        let row = cursor + 10;
        for (const [currency, amount] of entries) {
          const label = currency ? `${t.total} ${currency}` : t.total;
          doc.text(label, colUnit, row, { width: 80, align: 'right' });
          doc.text(fmtAmount(amount, currency || null), colSub, row, { width: 70, align: 'right' });
          row += 16;
        }
        cursor = row;
      }

      doc.y = cursor + 16;
      doc.x = left;

      // Notes
      if (ctx.notes) {
        doc.moveDown(1);
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#555555').text(t.notes);
        doc.font('Helvetica').fontSize(10).fillColor('#000000').text(ctx.notes, { width: doc.page.width - 100 });
      }

      // Signatures
      const sigTop = Math.max(doc.y + 50, doc.page.height - 180);
      doc.font('Helvetica-Bold').fontSize(12).fillColor('#000000').text(t.signaturesHeader, left, sigTop);

      const sigRow = sigTop + 40;
      const sigCol1 = left;
      const sigCol2 = left + colWidth + 10;

      const drawSignatureBlock = (label: string, x: number, y: number) => {
        doc.font('Helvetica-Bold').fontSize(9).fillColor('#555555').text(label, x, y);
        doc.moveTo(x, y + 30).lineTo(x + colWidth - 20, y + 30).strokeColor('#000000').stroke();
        doc.font('Helvetica').fontSize(8).fillColor('#666666').text(t.nameLine, x, y + 33);
        doc.moveTo(x, y + 65).lineTo(x + colWidth - 20, y + 65).strokeColor('#000000').stroke();
        doc.font('Helvetica').fontSize(8).fillColor('#666666').text(t.dateLine, x, y + 68);
      };

      if (ctx.documentType === 'outflow') {
        // Single authorization block for outflows — there is no receiver in a write-off.
        drawSignatureBlock(t.authorizedBy, sigCol1, sigRow);
      } else if (ctx.documentType === 'sale') {
        // A sale is signed by the seller and the customer.
        drawSignatureBlock(t.attendedBy, sigCol1, sigRow);
        drawSignatureBlock(t.customer, sigCol2, sigRow);
      } else {
        drawSignatureBlock(t.signedBy, sigCol1, sigRow);
        drawSignatureBlock(t.receivedBy, sigCol2, sigRow);
      }

      // Footer
      doc.font('Helvetica').fontSize(8).fillColor('#999999').text(
        t.autoGenerated,
        50,
        doc.page.height - 40,
        { align: 'center' },
      );

      // Void watermark for CANCELLED / REJECTED — stamped on every page so a
      // printed PDF can't be confused with a real receipt.
      if (VOID_STATUSES.has(ctx.status)) {
        const label = ctx.status === 'REJECTED' ? t.voidRejected : t.voidCancelled;
        const { width, height } = doc.page;
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
          doc.switchToPage(i);
          doc.save();
          doc.opacity(0.18);
          doc.rotate(-30, { origin: [width / 2, height / 2] });
          doc.font('Helvetica-Bold').fontSize(110).fillColor('#dc2626');
          doc.text(label, 0, height / 2 - 60, { width, align: 'center' });
          doc.restore();
        }
      }

      doc.end();
    });
  }
}
